# Generated by Django 2.1.7 on 2019-03-29 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('BIK', models.CharField(max_length=45)),
                ('INN', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Clinics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=45)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Clinics')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Doctors')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=45)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Clinics')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Doctors')),
            ],
        ),
    ]
