# Generated by Django 2.1.7 on 2019-03-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='inspections',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='inspections',
            name='clinic_id',
        ),
        migrations.RemoveField(
            model_name='inspections',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='inspections',
            name='code',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspections',
            name='inspection_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspections',
            name='patient_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='domain.Patients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='captures',
            name='inspection_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.Inspections', to_field='code'),
        ),
    ]
